name: master

on:
  push:
    branches: [ master, action ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: Lint
      run: cargo clippy -- -D warnings
      continue-on-error: true
      
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
      
    - name: Generate coverage file
      if: matrix.os == 'ubuntu-latest'
          && github.ref == 'refs/heads/master'
      run: |
        cargo install cargo-tarpaulin
        cargo tarpaulin --out Xml --verbose
        
    - name: Upload to Codecov
      if: matrix.os == 'ubuntu-latest'
          && github.ref == 'refs/heads/master'
      uses: codecov/codecov-action@v2.0.3
      with:
        file: cobertura.xml
   
